
## Step1, unified framework training, under different resource budgets
## starting from a pretrained dlrm model
CUDA_VISIBLE_DEVICES=0 python joint_train.py --arch-sparse-feature-size=16 --arch-mlp-bot="13-512-256-64-16" --arch-mlp-top="512-256-1" --data-generation=dataset --data-set=kaggle --raw-data-file=../kaggle/train.txt --processed-data-file=../kaggle/kaggleAdDisplayChallenge_processed.npz --loss-function=bce --round-targets=True --learning-rate=0.1 --mini-batch-size=128 --print-freq=1024 --test-freq=1024 --print-time --test-mini-batch-size=16384 --test-num-workers=16 --exp_mode rctrain --save-result-dir ../result/unify_budget_0.5/ --slr 0.05 --rlr 0.05 --load-model ../result/baseline_kaggle/best.pt --budget 0.5 --arch-interaction-op cat  --punit 1 --use-gpu >> unify_budget_0.5.txt 

CUDA_VISIBLE_DEVICES=1 python joint_train.py --arch-sparse-feature-size=16 --arch-mlp-bot="13-512-256-64-16" --arch-mlp-top="512-256-1" --data-generation=dataset --data-set=kaggle --raw-data-file=../kaggle/train.txt --processed-data-file=../kaggle/kaggleAdDisplayChallenge_processed.npz --loss-function=bce --round-targets=True --learning-rate=0.1 --mini-batch-size=128 --print-freq=1024 --test-freq=1024 --print-time --test-mini-batch-size=16384 --test-num-workers=16 --exp_mode rctrain --save-result-dir ../result/unify_budget_0.35/ --slr 0.05 --rlr 0.05 --load-model ../result/baseline_kaggle/best.pt --budget 0.35 --arch-interaction-op cat  --punit 1 --use-gpu >> unify_budget_0.35.txt

CUDA_VISIBLE_DEVICES=2 python joint_train.py --arch-sparse-feature-size=16 --arch-mlp-bot="13-512-256-64-16" --arch-mlp-top="512-256-1" --data-generation=dataset --data-set=kaggle --raw-data-file=../kaggle/train.txt --processed-data-file=../kaggle/kaggleAdDisplayChallenge_processed.npz --loss-function=bce --round-targets=True --learning-rate=0.1 --mini-batch-size=128 --print-freq=1024 --test-freq=1024 --print-time --test-mini-batch-size=16384 --test-num-workers=16 --exp_mode rctrain --save-result-dir ../result/unify_budget_0.29/ --slr 0.05 --rlr 0.05 --load-model ../result/baseline_kaggle/best.pt --budget 0.29 --arch-interaction-op cat  --punit 1 --use-gpu >> unify_budget_0.29.txt

CUDA_VISIBLE_DEVICES=3 python joint_train.py --arch-sparse-feature-size=16 --arch-mlp-bot="13-512-256-64-16" --arch-mlp-top="512-256-1" --data-generation=dataset --data-set=kaggle --raw-data-file=../kaggle/train.txt --processed-data-file=../kaggle/kaggleAdDisplayChallenge_processed.npz --loss-function=bce --round-targets=True --learning-rate=0.1 --mini-batch-size=128 --print-freq=1024 --test-freq=1024 --print-time --test-mini-batch-size=16384 --test-num-workers=16 --exp_mode rctrain --save-result-dir ../result/unify_budget_0.18/ --slr 0.05 --rlr 0.05 --load-model ../result/baseline_kaggle/best.pt --budget 0.18 --arch-interaction-op cat  --punit 1 --use-gpu >> unify_budget_0.18.txt

CUDA_VISIBLE_DEVICES=4 python joint_train.py --arch-sparse-feature-size=16 --arch-mlp-bot="13-512-256-64-16" --arch-mlp-top="512-256-1" --data-generation=dataset --data-set=kaggle --raw-data-file=../kaggle/train.txt --processed-data-file=../kaggle/kaggleAdDisplayChallenge_processed.npz --loss-function=bce --round-targets=True --learning-rate=0.1 --mini-batch-size=128 --print-freq=1024 --test-freq=1024 --print-time --test-mini-batch-size=16384 --test-num-workers=16 --exp_mode rctrain --save-result-dir ../result/unify_budget_0.1/ --slr 0.05 --rlr 0.05 --load-model ../result/baseline_kaggle/best.pt --budget 0.1 --arch-interaction-op cat  --punit 1 --use-gpu >> unify_budget_0.1.txt

CUDA_VISIBLE_DEVICES=5 python joint_train.py --arch-sparse-feature-size=16 --arch-mlp-bot="13-512-256-64-16" --arch-mlp-top="512-256-1" --data-generation=dataset --data-set=kaggle --raw-data-file=../kaggle/train.txt --processed-data-file=../kaggle/kaggleAdDisplayChallenge_processed.npz --loss-function=bce --round-targets=True --learning-rate=0.1 --mini-batch-size=128 --print-freq=1024 --test-freq=1024 --print-time --test-mini-batch-size=16384 --test-num-workers=16 --exp_mode rctrain --save-result-dir ../result/unify_budget_0.18/ --slr 0.05 --rlr 0.05 --load-model ../result/baseline_kaggle/best.pt --budget 0.05 --arch-interaction-op cat  --punit 1 --use-gpu >> unify_budget_0.05.txt

## Step2: export mask for zeroing out neurons under different resource budgets
# replace load-model argument with the last model that is trained in step1 
CUDA_VISIBLE_DEVICES=0 python dlrm_generate_mask.py --arch-sparse-feature-size=16 --arch-mlp-bot="13-512-256-64-16" --arch-mlp-top="512-256-1" --data-generation=dataset --data-set=kaggle  --raw-data-file=../kaggle/train.txt  --processed-data-file=../kaggle/kaggleAdDisplayChallenge_processed.npz --loss-function=bce --round-targets=True --learning-rate=0.1 --mini-batch-size=128 --print-freq=1024 --test-freq=1024 --print-time --test-mini-batch-size=16384 --test-num-workers=16 --save-result-dir ../result/unify_budget_0.5/ --arch-interaction-op cat --load-model ../result/unify_budget_0.5/last_model.pt --use-gpu 

CUDA_VISIBLE_DEVICES=1 python dlrm_generate_mask.py --arch-sparse-feature-size=16 --arch-mlp-bot="13-512-256-64-16" --arch-mlp-top="512-256-1" --data-generation=dataset --data-set=kaggle  --raw-data-file=../kaggle/train.txt  --processed-data-file=../kaggle/kaggleAdDisplayChallenge_processed.npz --loss-function=bce --round-targets=True --learning-rate=0.1 --mini-batch-size=128 --print-freq=1024 --test-freq=1024 --print-time --test-mini-batch-size=16384 --test-num-workers=16 --save-result-dir ../result/unify_budget_0.35/ --arch-interaction-op cat --load-model ../result/unify_budget_0.35/last_model.pt --use-gpu 

CUDA_VISIBLE_DEVICES=2 python dlrm_generate_mask.py --arch-sparse-feature-size=16 --arch-mlp-bot="13-512-256-64-16" --arch-mlp-top="512-256-1" --data-generation=dataset --data-set=kaggle  --raw-data-file=../kaggle/train.txt  --processed-data-file=../kaggle/kaggleAdDisplayChallenge_processed.npz --loss-function=bce --round-targets=True --learning-rate=0.1 --mini-batch-size=128 --print-freq=1024 --test-freq=1024 --print-time --test-mini-batch-size=16384 --test-num-workers=16 --save-result-dir ../result/unify_budget_0.29/ --arch-interaction-op cat --load-model ../result/unify_budget_0.29/last_model.pt --use-gpu 

CUDA_VISIBLE_DEVICES=3 python dlrm_generate_mask.py --arch-sparse-feature-size=16 --arch-mlp-bot="13-512-256-64-16" --arch-mlp-top="512-256-1" --data-generation=dataset --data-set=kaggle  --raw-data-file=../kaggle/train.txt  --processed-data-file=../kaggle/kaggleAdDisplayChallenge_processed.npz --loss-function=bce --round-targets=True --learning-rate=0.1 --mini-batch-size=128 --print-freq=1024 --test-freq=1024 --print-time --test-mini-batch-size=16384 --test-num-workers=16 --save-result-dir ../result/unify_budget_0.18/ --arch-interaction-op cat --load-model ../result/unify_budget_0.18/last_model.pt --use-gpu 

CUDA_VISIBLE_DEVICES=4 python dlrm_generate_mask.py --arch-sparse-feature-size=16 --arch-mlp-bot="13-512-256-64-16" --arch-mlp-top="512-256-1" --data-generation=dataset --data-set=kaggle  --raw-data-file=../kaggle/train.txt  --processed-data-file=../kaggle/kaggleAdDisplayChallenge_processed.npz --loss-function=bce --round-targets=True --learning-rate=0.1 --mini-batch-size=128 --print-freq=1024 --test-freq=1024 --print-time --test-mini-batch-size=16384 --test-num-workers=16 --save-result-dir ../result/unify_budget_0.1/ --arch-interaction-op cat --load-model ../result/unify_budget_0.1/last_model.pt --use-gpu 

CUDA_VISIBLE_DEVICES=5 python dlrm_generate_mask.py --arch-sparse-feature-size=16 --arch-mlp-bot="13-512-256-64-16" --arch-mlp-top="512-256-1" --data-generation=dataset --data-set=kaggle  --raw-data-file=../kaggle/train.txt  --processed-data-file=../kaggle/kaggleAdDisplayChallenge_processed.npz --loss-function=bce --round-targets=True --learning-rate=0.1 --mini-batch-size=128 --print-freq=1024 --test-freq=1024 --print-time --test-mini-batch-size=16384 --test-num-workers=16 --save-result-dir ../result/unify_budget_0.05/ --arch-interaction-op cat --load-model ../result/unify_budget_0.05/last_model.pt --use-gpu 

## Step 3: finetuning under different resource budgets
CUDA_VISIBLE_DEVICES=0 python finetune.py --arch-sparse-feature-size=16 --arch-mlp-bot="13-512-256-64-16" --arch-mlp-top="512-256-1" --data-generation=dataset --data-set=kaggle --raw-data-file=../kaggle/train.txt --processed-data-file=../kaggle/kaggleAdDisplayChallenge_processed.npz --loss-function=bce --round-targets=True --learning-rate=0.1 --mini-batch-size=128 --print-freq=1024 --test-freq=1024 --print-time --test-mini-batch-size=16384 --test-num-workers=16 --save_result_dir ../result/unify_budget_0.5_finetune/--arch-interaction-op cat  --mask_file ../result/unify_budget_0.5/mask.pkl --use-gpu >> unify_cat_budget_0.5_finetune.txt

CUDA_VISIBLE_DEVICES=1 python finetune.py --arch-sparse-feature-size=16 --arch-mlp-bot="13-512-256-64-16" --arch-mlp-top="512-256-1" --data-generation=dataset --data-set=kaggle --raw-data-file=../kaggle/train.txt --processed-data-file=../kaggle/kaggleAdDisplayChallenge_processed.npz --loss-function=bce --round-targets=True --learning-rate=0.1 --mini-batch-size=128 --print-freq=1024 --test-freq=1024 --print-time --test-mini-batch-size=16384 --test-num-workers=16 --save_result_dir ../result/unify_budget_0.35_finetune/--arch-interaction-op cat  --mask_file ../result/unify_budget_0.35/mask.pkl --use-gpu >> unify_cat_budget_0.35_finetune.txt

CUDA_VISIBLE_DEVICES=0 python finetune.py --arch-sparse-feature-size=16 --arch-mlp-bot="13-512-256-64-16" --arch-mlp-top="512-256-1" --data-generation=dataset --data-set=kaggle --raw-data-file=../kaggle/train.txt --processed-data-file=../kaggle/kaggleAdDisplayChallenge_processed.npz --loss-function=bce --round-targets=True --learning-rate=0.1 --mini-batch-size=128 --print-freq=1024 --test-freq=1024 --print-time --test-mini-batch-size=16384 --test-num-workers=16 --save_result_dir ../result/unify_budget_0.29_finetune/--arch-interaction-op cat  --mask_file ../result/unify_budget_0.29/mask.pkl --use-gpu >> unify_cat_budget_0.29_finetune.txt

CUDA_VISIBLE_DEVICES=0 python finetune.py --arch-sparse-feature-size=16 --arch-mlp-bot="13-512-256-64-16" --arch-mlp-top="512-256-1" --data-generation=dataset --data-set=kaggle --raw-data-file=../kaggle/train.txt --processed-data-file=../kaggle/kaggleAdDisplayChallenge_processed.npz --loss-function=bce --round-targets=True --learning-rate=0.1 --mini-batch-size=128 --print-freq=1024 --test-freq=1024 --print-time --test-mini-batch-size=16384 --test-num-workers=16 --save_result_dir ../result/unify_budget_0.18_finetune/--arch-interaction-op cat  --mask_file ../result/unify_budget_0.18/mask.pkl --use-gpu >> unify_cat_budget_0.18_finetune.txt

CUDA_VISIBLE_DEVICES=0 python finetune.py --arch-sparse-feature-size=16 --arch-mlp-bot="13-512-256-64-16" --arch-mlp-top="512-256-1" --data-generation=dataset --data-set=kaggle --raw-data-file=../kaggle/train.txt --processed-data-file=../kaggle/kaggleAdDisplayChallenge_processed.npz --loss-function=bce --round-targets=True --learning-rate=0.1 --mini-batch-size=128 --print-freq=1024 --test-freq=1024 --print-time --test-mini-batch-size=16384 --test-num-workers=16 --save_result_dir ../result/unify_budget_0.1_finetune/--arch-interaction-op cat  --mask_file ../result/unify_budget_0.1/mask.pkl --use-gpu >> unify_cat_budget_0.1_finetune.txt

CUDA_VISIBLE_DEVICES=0 python finetune.py --arch-sparse-feature-size=16 --arch-mlp-bot="13-512-256-64-16" --arch-mlp-top="512-256-1" --data-generation=dataset --data-set=kaggle --raw-data-file=../kaggle/train.txt --processed-data-file=../kaggle/kaggleAdDisplayChallenge_processed.npz --loss-function=bce --round-targets=True --learning-rate=0.1 --mini-batch-size=128 --print-freq=1024 --test-freq=1024 --print-time --test-mini-batch-size=16384 --test-num-workers=16 --save_result_dir ../result/unify_budget_0.05_finetune/--arch-interaction-op cat  --mask_file ../result/unify_budget_0.05/mask.pkl --use-gpu >> unify_cat_budget_0.05_finetune.txt

